# ============================================================================
#  Sony HB-F1XV MSX2+ Emulator
#  Copyright (c) 2026 Patrick Shim <patrick.shim@live.co.kr>
#
#  LEGAL NOTICE - Personal reference only.
#  This source code is made available solely for personal, non-commercial
#  reference and educational study. Commercial use, sale, or redistribution
#  for profit is not permitted without the author's written consent.
#  Provided "AS IS", without warranty of any kind.
#  Proprietary BIOS/ROM/disk assets remain the property of their respective
#  rights holders and are NOT licensed by this notice.
# ============================================================================

# tools/capture/screen-mode-sprite-run.ps1 — M51 EG-3: the 13-scenario screen-mode + sprite A/B
# vs openMSX, rebuilt from the M41 pieces after the original guest assets were
# cleaned with debug/ (the manifest-driven tools/capture/av-scenarios-run.ps1 rows were lost):
#   * carts regenerated by tools/gen/video-cart.py (deterministic),
#   * per-scenario GEOMETRY via tools/analyze/video-ab.py (--geom, incl. the
#     512-wide -doublesize openMSX capture the M41-S2 findings resolved),
#   * ours = --debug-session --cart1 --frames N --dump-frame.

param(
    [string]$Headless = "build/Debug/sony_msx_headless.exe",
    [string]$BiosDir = "bios",
    [string]$CartDir = "debug/m51/m41-carts",
    [string]$OutDir = "debug/m51/m41-ab",
    [int]$Frames = 700,
    [int]$Seconds = 10
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path ".").Path

# scenario -> m41-video-ab geometry class
$geom = @{
    "m0_text1"      = "text240"
    "m1_g1"         = "g256_192"
    "m2_g2"         = "g256_192"
    "m4_g3"         = "g256_192"
    "m5_g4"         = "g256_212"
    "m6_g5"         = "g512_212"
    "m7_g6"         = "g512_212"
    "m8_g7"         = "g256_212"
    "m12_yjk"       = "g256_212"
    "m10_yjkyae"    = "g256_212"
    "sp1_single"    = "g256_192"  # SCREEN2 sprite mode 1 (192-line class)
    "sp2_double"    = "g256_212"
    "sp3_collision" = "g256_212"
}

function To-WslPath([string]$winPath) {
    $abs = (Resolve-Path $winPath).Path
    return (wsl -e wslpath -a "$abs").Trim()
}

New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
$rows = @()

foreach ($rom in (Get-ChildItem -Path $CartDir -Filter "*.rom" | Sort-Object Name)) {
    $id = [System.IO.Path]::GetFileNameWithoutExtension($rom.Name)
    if (-not $geom.ContainsKey($id)) { continue }
    $g = $geom[$id]
    $sdir = Join-Path $OutDir $id
    New-Item -ItemType Directory -Path $sdir -Force | Out-Null
    Write-Host "=== $id [$g] ===" -ForegroundColor Cyan

    # ours
    $eap = $ErrorActionPreference; $ErrorActionPreference = "Continue"
    & $Headless --debug-session $BiosDir 0 --stock --frames $Frames `
        --cart1 $rom.FullName --debug-root $sdir --dump-frame frame 2>$null | Out-Null
    python tools/convert/frame-to-png.py (Join-Path $sdir "frames/frame") -o (Join-Path $sdir "ours.png") 2>$null | Out-Null
    $ErrorActionPreference = $eap

    # openMSX raw (doublesize for the 512-wide classes)
    $dbl = if ($g -eq "g512_212") { "-doublesize" } else { "" }
    $romWsl = To-WslPath $rom.FullName
    $outWsl = (wsl -e wslpath -a "$((Resolve-Path $sdir).Path)").Trim() + "/omx_raw.png"
    $tcl = @"
after time $Seconds {
  screenshot -raw $dbl /tmp/m51_eg3.png
  exit
}
"@
    $enc = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($tcl))
    $cmd = "echo $enc | base64 -d > /tmp/m51_eg3.tcl && " +
           "timeout -k 3 90 openmsx -machine Sony_HB-F1XV -cart '$romWsl' -script /tmp/m51_eg3.tcl >/dev/null 2>&1; " +
           "cp /tmp/m51_eg3.png '$outWsl'"
    wsl -e bash -lc $cmd | Out-Null

    # geometry-aware diff
    $eap = $ErrorActionPreference; $ErrorActionPreference = "Continue"
    $line = python tools/analyze/video-ab.py --ours (Join-Path $sdir "ours.png") `
        --omx (Join-Path $sdir "omx_raw.png") --geom $g `
        --out (Join-Path $sdir ($id + "_ab.png")) --label $id 2>&1
    $ErrorActionPreference = $eap
    Write-Host "  $line"
    $pct = ($line | Select-String "pct_mismatch=([\d.]+)").Matches.Groups[1].Value
    $verd = ($line | Select-String "verdict=(\w+)").Matches.Groups[1].Value
    $rows += [pscustomobject]@{ scenario = $id; geom = $g; pct_mismatch = $pct; verdict = $verd }
}

$report = Join-Path $OutDir "m51-eg3-report.md"
$lines = @("## M51 EG-3 13-scenario screen/sprite A/B (ours vs openMSX 19.1 Sony_HB-F1XV)", "",
           "| scenario | geom | pct_mismatch | verdict |", "|---|---|---|---|")
foreach ($r in $rows) { $lines += "| $($r.scenario) | $($r.geom) | $($r.pct_mismatch) | $($r.verdict) |" }
Set-Content -LiteralPath $report -Value ($lines -join [Environment]::NewLine) -Encoding UTF8
Write-Host "Report: $report" -ForegroundColor Green
$rows | Format-Table -AutoSize
